# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e05e0c63e25a2a37a9e5b3bffa834aa602327c001c30ac4721693d8ec050fe42f8ddbdfbfeac2c343b657574400f8ce13ececa76ea45bbf0ea0ee8284819b511

test:
  secret_key_base: d38e26a8068c0b0bb11a522170f13ed6c56ebf79d136bcf50c8fdea69d519e493b7ac4356fb9ce5f69c4cf09eaf1e7289c659dd010febe0f441fefebdfffbf88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
